create table
  public.team (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    name character varying not null,
    max_height double precision null default '0'::double precision,
    total_height double precision null default '0'::double precision,
    total_distance double precision null default '0'::double precision,
    constraint team_pkey primary key (id)
  ) tablespace pg_default;